query Post($cityID: Int, $activityID: Int){
  terms(city: $cityID, activity: $activityID, ageGroup: 11 ){
    id
    post_title
    post_meta{
      meta_id
      meta_key
      meta_value
    }
  }
}